config/routes.rb
Rails.application.routes.draw do
  resources :dogs, only: %i[index new create destroy]

  root "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  def good_boy?
    good_boy || good_boy == "TRUE"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.new(dog_params)

    return redirect_to dogs_url, notice: "Dogs uploaded." if dog.save
    render :new
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_url, notice: "Dog successfully deleted."
  end

  private

  def dog_params
    params.require(:dog).permit(:id, :file, :name, :color, :size, :good_boy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_file_form.html.erb
<%= form_with scope: :dog, url: dogs_path, local: true do |form| %>
  <p>
    <%= form.label :file %><br>
    <%= form.file_field :file %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/dogs/_form.html.erb
<%= form_with scope: :dog, url: dogs_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </p>
  <p>
    <%= form.label :size %><br>
    <%= form.text_field :size %>
  </p>
  <p>
    <%= form.label :good_boy %><br>
    <%= form.check_box :good_boy %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/dogs/index.html.erb
<h1>Your dogs:</h1>

<% if @dogs&.any? %>
  <ul>
    <% @dogs.each do |dog| %>
      <li>
        <div><b>Name:</b> <span><%= dog.name %></span></div>
        <div><b>Color:</b> <span><%= dog.color %></span></div>
        <div><b>Size:</b> <span><%= dog.size %></span></div>
        <div><b>Is a good boy / girl?:</b> <span><%= dog.good_boy? ? "yes" : "no" %></span></div>
        <div>
          <%= link_to "Delete dog", dog_path(dog), method: :delete %>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No dogs :(</p>
<% end %>

<footer>
  <%= link_to "Get dogs!", new_dog_path %>
</footer>

app/views/dogs/new.html.erb
<h1>New dogs:</h1>

<%= render partial: "form" %>
<%# render partial: "file_form" %>

<footer>
  <%= link_to "See my dogs", "/" %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogSpreadsheet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>